language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache/files"

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 5.3
      dist: precise
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
      env: SYMFONY_VERSION="2.7.*"
    - php: 7.1
      env: SYMFONY_VERSION="2.8.*"
    - php: 7.1
      env: SYMFONY_VERSION="3.1.*"

before_install:
    - if [[ ! $TRAVIS_PHP_VERSION = hhvm* ]]; then INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; else INI_FILE=/etc/hhvm/php.ini; fi
    - echo memory_limit = -1 >> $INI_FILE
    - if [[ "$SYMFONY_VERSION" != "" ]]; then export SYMFONY_DEPRECATIONS_HELPER=weak && composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: composer update $COMPOSER_FLAGS

script: phpunit --coverage-clover clover

after_success: curl -sL https://bit.ly/artifact-uploader | php
