language: php

php:
  - 5.5
  - 7.0
  - hhvm

before_script: composer install --dev

script: phpunit --coverage-clover clover --coverage-text

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php
